/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ua.goit;

import com.google.gson.Gson;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main( String[] args ) {
        User user = new User("Petryk", "Pyatochkyn");
        System.out.println(new Gson().toJson(user));
    }
}
